name: Release

on:
  push:
    branches: 
    #  - main
      - updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t willrock/js-actions-app
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - run: docker push willrock/js-actions-app


helm-lint:
  name: Helm lint and release
  runs-on: ubuntu-latest
  needs: build

  steps:
    - uses: actions/checkout@v2
    - name: Helm Lint
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint ./helm
    - name: Helm install
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade --install node-app ./helm
        kubeconfig: '${{ secrets.KUBECONFIG }}' 