name: Integration

on:
  push:
    branches:
    #  - main
      - updates
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'npm'
      - run: npm i
      - run: npm run build

  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 12.x
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '12.x'
  #         cache: 'npm'
  #     - run: npm i
  #     - run: npm run test
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t willrock/js-actions-app
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - run: docker push willrock/js-actions-app